/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CheckOut } from "./CheckOut";
import { CheckOutCountArgs } from "./CheckOutCountArgs";
import { CheckOutFindManyArgs } from "./CheckOutFindManyArgs";
import { CheckOutFindUniqueArgs } from "./CheckOutFindUniqueArgs";
import { CreateCheckOutArgs } from "./CreateCheckOutArgs";
import { UpdateCheckOutArgs } from "./UpdateCheckOutArgs";
import { DeleteCheckOutArgs } from "./DeleteCheckOutArgs";
import { Room } from "../../room/base/Room";
import { Customer } from "../../customer/base/Customer";
import { CheckOutService } from "../checkOut.service";
@graphql.Resolver(() => CheckOut)
export class CheckOutResolverBase {
  constructor(protected readonly service: CheckOutService) {}

  async _checkOutsMeta(
    @graphql.Args() args: CheckOutCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [CheckOut])
  async checkOuts(
    @graphql.Args() args: CheckOutFindManyArgs
  ): Promise<CheckOut[]> {
    return this.service.checkOuts(args);
  }

  @graphql.Query(() => CheckOut, { nullable: true })
  async checkOut(
    @graphql.Args() args: CheckOutFindUniqueArgs
  ): Promise<CheckOut | null> {
    const result = await this.service.checkOut(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => CheckOut)
  async createCheckOut(
    @graphql.Args() args: CreateCheckOutArgs
  ): Promise<CheckOut> {
    return await this.service.createCheckOut({
      ...args,
      data: {
        ...args.data,

        room: args.data.room
          ? {
              connect: args.data.room,
            }
          : undefined,

        customer: args.data.customer
          ? {
              connect: args.data.customer,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => CheckOut)
  async updateCheckOut(
    @graphql.Args() args: UpdateCheckOutArgs
  ): Promise<CheckOut | null> {
    try {
      return await this.service.updateCheckOut({
        ...args,
        data: {
          ...args.data,

          room: args.data.room
            ? {
                connect: args.data.room,
              }
            : undefined,

          customer: args.data.customer
            ? {
                connect: args.data.customer,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => CheckOut)
  async deleteCheckOut(
    @graphql.Args() args: DeleteCheckOutArgs
  ): Promise<CheckOut | null> {
    try {
      return await this.service.deleteCheckOut(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Room, {
    nullable: true,
    name: "room",
  })
  async getRoom(@graphql.Parent() parent: CheckOut): Promise<Room | null> {
    const result = await this.service.getRoom(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Customer, {
    nullable: true,
    name: "customer",
  })
  async getCustomer(
    @graphql.Parent() parent: CheckOut
  ): Promise<Customer | null> {
    const result = await this.service.getCustomer(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
