/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RateService } from "../rate.service";
import { RateCreateInput } from "./RateCreateInput";
import { Rate } from "./Rate";
import { RateFindManyArgs } from "./RateFindManyArgs";
import { RateWhereUniqueInput } from "./RateWhereUniqueInput";
import { RateUpdateInput } from "./RateUpdateInput";

export class RateControllerBase {
  constructor(protected readonly service: RateService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Rate })
  async createRate(@common.Body() data: RateCreateInput): Promise<Rate> {
    return await this.service.createRate({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        roomType: true,
        price: true,
        season: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Rate] })
  @ApiNestedQuery(RateFindManyArgs)
  async rates(@common.Req() request: Request): Promise<Rate[]> {
    const args = plainToClass(RateFindManyArgs, request.query);
    return this.service.rates({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        roomType: true,
        price: true,
        season: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Rate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async rate(
    @common.Param() params: RateWhereUniqueInput
  ): Promise<Rate | null> {
    const result = await this.service.rate({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        roomType: true,
        price: true,
        season: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Rate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRate(
    @common.Param() params: RateWhereUniqueInput,
    @common.Body() data: RateUpdateInput
  ): Promise<Rate | null> {
    try {
      return await this.service.updateRate({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          roomType: true,
          price: true,
          season: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Rate })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRate(
    @common.Param() params: RateWhereUniqueInput
  ): Promise<Rate | null> {
    try {
      return await this.service.deleteRate({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          roomType: true,
          price: true,
          season: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
