/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RoomStatusService } from "../roomStatus.service";
import { RoomStatusCreateInput } from "./RoomStatusCreateInput";
import { RoomStatus } from "./RoomStatus";
import { RoomStatusFindManyArgs } from "./RoomStatusFindManyArgs";
import { RoomStatusWhereUniqueInput } from "./RoomStatusWhereUniqueInput";
import { RoomStatusUpdateInput } from "./RoomStatusUpdateInput";

export class RoomStatusControllerBase {
  constructor(protected readonly service: RoomStatusService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RoomStatus })
  async createRoomStatus(
    @common.Body() data: RoomStatusCreateInput
  ): Promise<RoomStatus> {
    return await this.service.createRoomStatus({
      data: {
        ...data,

        room: data.room
          ? {
              connect: data.room,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,

        room: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [RoomStatus] })
  @ApiNestedQuery(RoomStatusFindManyArgs)
  async roomStatuses(@common.Req() request: Request): Promise<RoomStatus[]> {
    const args = plainToClass(RoomStatusFindManyArgs, request.query);
    return this.service.roomStatuses({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,

        room: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RoomStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async roomStatus(
    @common.Param() params: RoomStatusWhereUniqueInput
  ): Promise<RoomStatus | null> {
    const result = await this.service.roomStatus({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        status: true,

        room: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RoomStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRoomStatus(
    @common.Param() params: RoomStatusWhereUniqueInput,
    @common.Body() data: RoomStatusUpdateInput
  ): Promise<RoomStatus | null> {
    try {
      return await this.service.updateRoomStatus({
        where: params,
        data: {
          ...data,

          room: data.room
            ? {
                connect: data.room,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,

          room: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RoomStatus })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRoomStatus(
    @common.Param() params: RoomStatusWhereUniqueInput
  ): Promise<RoomStatus | null> {
    try {
      return await this.service.deleteRoomStatus({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          status: true,

          room: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
